language: cpp
compiler: gcc
addons:
  apt:
    packages:
    - linux-libc-dev:i386
    - libmysqlclient-dev:i386
    - libmysql++3:i386
    - gcc-4.6-multilib
    - g++-4.6-multilib
before_install:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
script:
  - make NIGHTLY=1 -f makefile
after_success:
  - mkdir accounts logs save scripts
  - tar -czvf SphereSvr-Linux32.tar.gz accounts logs save scripts spheresvr src/sphere.ini src/sphereCrypt.ini
  - curl -T SphereSvr-Linux32.tar.gz -u $FTP_USER:$FTP_PASSWORD ftp://spherecommunity.net
notifications:
  email: false