language: cpp
compiler: gcc
env:
  - BUILD_CMD="make NIGHTLY=1"
git:
  depth: false
notifications:
  email: false
addons:
  apt:
    packages:
    - gcc-multilib
    - g++-multilib
    - libmysqlclient-dev:i386
  coverity_scan:
    project:
      name: "Sphereserver/Source"
      description: "Game server for Ultima Online"
    notification_email: null@null
    build_command: $BUILD_CMD
    branch_pattern: master
script:
  - if [ $COVERITY_SCAN_BRANCH != 1 ]; then $BUILD_CMD; fi