language: cpp
compiler: gcc
addons:
  apt:
    sources:
    - mysql-5.7-trusty
    packages:
    - libmysql++-dev:i386
    - gcc-multilib
    - g++-multilib
git:
  depth: false
notifications:
  email: false
script:
  - make NIGHTLY=1 -f makefile
#after_success:
#  - mkdir accounts logs save scripts
#  - tar -czvf SphereSvr-Linux32.tar.gz accounts/ logs/ save/ scripts/ spheresvr -C src/ sphere.ini sphereCrypt.ini
#  - curl -T SphereSvr-Linux32.tar.gz -u $FTP_USER:$FTP_PASSWORD $FTP_SERVER