language: cpp
compiler: gcc
env:
  - BUILD_CMD="make NIGHTLY=1 -f makefile"
git:
  depth: false
notifications:
  email: false
addons:
  apt:
    sources:
    - mysql-5.7-trusty
    packages:
    - libmysql++-dev:i386
    - gcc-multilib
    - g++-multilib
  coverity_scan:
    project:
      name: "Sphere Server"
      description: "Game server for Ultima Online"
    notification_email: " "
    build_command: $BUILD_CMD
    branch_pattern: master
script:
  - if [ $COVERITY_SCAN_BRANCH != 1 ]; then $BUILD_CMD; fi