version: 0.56.4.{build}
configuration: Nightly
pull_requests:
  do_not_increment_build_number: true
image:
  - Visual Studio 2015
  - Ubuntu

for:
  -
    matrix:
      only:
        - image: Visual Studio 2015
    build:
      project: SphereSvr.vcxproj
      verbosity: minimal
    after_build:
      - cmd: mkdir accounts logs save scripts
      - cmd: 7z a SphereSvr-Win32.zip accounts\ logs\ save\ scripts\ %APPVEYOR_BUILD_FOLDER%\%CONFIGURATION%\SphereSvr.exe %APPVEYOR_BUILD_FOLDER%\src\sphere.ini %APPVEYOR_BUILD_FOLDER%\src\sphereCrypt.ini %APPVEYOR_BUILD_FOLDER%\src\common\mysql\lib\libmysql.dll
    artifacts:
      - path: SphereSvr-Win32.zip
        name: SphereSvr
  -
    matrix:
      only:
        - image: Ubuntu
    install:
      - sh: sudo apt-get -qq install gcc-multilib g++-multilib libmysql++-dev:i386 > /dev/null
    before_build:
      - sh: lsb_release -d
      - sh: gcc --version
    build_script:
      - sh: make NIGHTLY=1 -f makefile
    after_build:
      - sh: mkdir accounts logs save scripts
      - sh: tar -czvf SphereSvr-Linux32.tar.gz accounts/ logs/ save/ scripts/ spheresvr -C src/ sphere.ini sphereCrypt.ini
      - echo "set ssl:verify-certificate no" >> ~/.lftprc
    artifacts:
      - path: SphereSvr-Linux32.tar.gz
        name: SphereSvr

deploy:
  provider: FTP
  protocol: ftp
  host:
    secure: LjYrCGlwCyEGfBJ2fVvCF9pAlSlsob0eZaUnKrFWJTs=
  username:
    secure: UAZaqnbj2s8C/ObEXIg6xA==
  password:
    secure: 0tC8NEgCp8IBChlZ0ssFdzgwkD+iX3FykjKaRQe+03k=